name: Lint

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Check for linting errors
        run: poetry run ruff check .

      - name: Block pull request if linting fails
        if: ${{ failure() }}
        uses: reviewdog/action-annotate@v1
        with:
          annotation_level: failure
          tool_name: Ruff Linter
          fail_on_error: true
